FROM --platform=linux/amd64 899955329535.dkr.ecr.us-west-2.amazonaws.com/python:latest

COPY . /app/
WORKDIR /app

# Install `pip` and needed Python packages from `requirements.txt`
RUN pip install --upgrade pip

RUN pip install -r requirements.txt

ENV FLASK_RUN_PORT=5000
ENV FLASK_RUN_HOST=0.0.0.0
EXPOSE 5000
ENTRYPOINT [ "flask", "--app", "app:create_app", "run" ]