apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-villas-linux-deployment
  namespace: villas-deploy
  labels:
    app: eks-villas-linux-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-villas-linux-app
  template:
    metadata:
      labels:
        app: eks-villas-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
      containers:
      - name: villas
        image: 899955329535.dkr.ecr.us-west-2.amazonaws.com/villas-ecr:villas
        ports:
        - name: http
          containerPort: 5000
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux