apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: "{RDS_DB_INSTANCE_NAME}"
  namespace: "{VILLAS_NAMESPACE}"
spec:
  allocatedStorage: 2
  autoMinorVersionUpgrade: true
  dbInstanceClass: db.t4g.micro
  dbInstanceIdentifier: "{RDS_DB_INSTANCE_NAME}"
  dbName: "{RDS_DB_NAME}"
  dbSubnetGroupName: "{RDS_SUBNET_GROUP_NAME}"
  engine: postgres
  engineVersion: "14"
  masterUsername: "{RDS_DB_USERNAME}"
  masterUserPassword:
    namespace: "{VILLAS_NAMESPACE}"
    name: "villas-rds-password"
    key: password
  publiclyAccessible: false
  vpcSecurityGroupIDs:
    - "{RDS_SECURITY_GROUP_ID}"