apiVersion: v1
data:
  USE_POD_ENV_CONFIG: "True"
  DB_USERNAME: {DB_USERNAME}
  DB_PASSWORD: {DB_PASSWORD}
  DB_NAME: {DB_NAME}
  DB_HOST: "{RDS_DB_INSTANCE_HOST}:{RDS_DB_INSTANCE_PORT}"
  AUTH0_BACKEND_CLIENT_ID: {AUTH0_BACKEND_CLIENT_ID}
  AUTH0_BACKEND_CLIENT_SECRET: {AUTH0_BACKEND_CLIENT_SECRET}
  AUTH0_MANAGEMENT_API_AUDIENCE: {AUTH0_MANAGEMENT_API_AUDIENCE}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: dbconfig
  namespace: {VILLAS_NAMESPACE}