apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: {RDS_DB_INSTANCE_NAME}
  namespace: {VILLAS_NAMESPACE}
spec:
  allocatedStorage: 5
  autoMinorVersionUpgrade: true
  backupRetentionPeriod: 7
  dbInstanceClass: db.t4g.micro
  dbInstanceIdentifier: {RDS_DB_INSTANCE_NAME}
  dbName: {DB_NAME}
  dbSubnetGroupName: {RDS_SUBNET_GROUP_NAME}
  engine: postgres
  engineVersion: "14"
  masterUsername: {DB_USERNAME}
  masterUserPassword:
    namespace: {VILLAS_NAMESPACE}
    name: villas-rds-password
    key: password
  publiclyAccessible: false
  multiAZ: true
  storageEncrypted: false
  storageType: gp2
  vpcSecurityGroupIDs:
    - {RDS_SECURITY_GROUP_ID}