"""Initial migration.

Revision ID: 474fd18d285b
Revises: 
Create Date: 2023-10-10 18:17:30.584389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474fd18d285b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('province_state',
    sa.Column('id', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('villa_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('home_address_line_1', sa.String(length=100), nullable=True),
    sa.Column('home_address_line_2', sa.String(length=100), nullable=True),
    sa.Column('home_city', sa.String(length=100), nullable=True),
    sa.Column('home_province', sa.String(length=2), nullable=True),
    sa.Column('home_country', sa.String(length=3), nullable=True),
    sa.Column('home_postal_code', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['home_country'], ['country.id'], ),
    sa.ForeignKeyConstraint(['home_province'], ['province_state.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('villa_user')
    op.drop_table('province_state')
    op.drop_table('country')
    # ### end Alembic commands ###
